# Generated by Django 4.1.3 on 2022-11-09 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_chapter_like_counter_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'verbose_name': 'Глава', 'verbose_name_plural': 'Главы'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AlterModelOptions(
            name='title',
            options={'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AlterModelOptions(
            name='volume',
            options={'verbose_name': 'Том', 'verbose_name_plural': 'Томы'},
        ),
        migrations.AlterField(
            model_name='chapter',
            name='content',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='like_counter',
            field=models.IntegerField(default=0, verbose_name='Кол-во лайков'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='number',
            field=models.IntegerField(verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='views_counter',
            field=models.IntegerField(default=0, verbose_name='Кол-во просмотров'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='volume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='book.volume', verbose_name='Том'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=25, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='title',
            name='alt_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Альтернативное название'),
        ),
        migrations.AlterField(
            model_name='title',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='title',
            name='eng_name',
            field=models.CharField(max_length=150, verbose_name='Английское название'),
        ),
        migrations.AlterField(
            model_name='title',
            name='ru_name',
            field=models.CharField(max_length=150, verbose_name='Русское название'),
        ),
        migrations.AlterField(
            model_name='title',
            name='tags',
            field=models.ManyToManyField(to='book.tag', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название тома'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='number',
            field=models.IntegerField(verbose_name='Номер тома'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='price',
            field=models.FloatField(default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volumes', to='book.title', verbose_name='Название книги'),
        ),
    ]
