# Generated by Django 4.1.3 on 2022-11-09 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_chapter_options_alter_tag_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='number',
            field=models.IntegerField(verbose_name='Номер главы'),
        ),
    ]
